# Generate two builds with both GCC and Clang
language: c
compiler:
  - gcc
  - clang


# Activate builds only for master
branches:
  only:
    - master


# Use Docker image containing my other repos Clog and CUTE
services:
  - docker
before_install:
  - docker pull joh1/clog_cute


script:
  - make
  - make test
