# This is a C project
language: c

# Generate two builds with both GCC and Clang
compiler:
  - gcc
  - clang

# Activate builds only for master
branches:
  only:
    - master

# Enable Docker
services:
  - docker


# Use Docker image containing my other repos Clog & CUTE
before_install:
  - docker pull joh1/clog_cute
  - docker run --detach --interactive --name clog_cute joh1/clog_cute

# Fetch the project from github inside the container
install:
  - docker exec clog_cute git clone https://github.com/Moonstroke/CODS.git cods


# Launch the tests from the container
script:
  - docker exec clog_cute /bin/sh -c 'cd cods && make && make test'
