language: c
compiler:
  - gcc
  - clang


# Activate builds only for master
branches:
  only:
    - master


# We need to be root to install the dependencies
sudo: true

install:
  - make get-deps

script:
  - make
  - make test
