language: c
compiler:
  - gcc
  - clang


# Activate builds only for master
branches:
  only:
    - master


# We need to be root to install the dependencies
sudo: true

install:
  # Install dependencies from the bash script
  - sudo ./install_deps.sh

script:
  - make
  - make test
